name: rohd_devtools_extension
description: "DevTool extension on ROHD."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-16.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rohd:
    path: ../../rohd
  # devtools_shared: ^6.0.0
  devtools_extensions: ^0.0.6
  devtools_app_shared: ^0.0.4
  vm_service: ^11.9.0
  flutter_simple_treeview: ^3.0.2
  equatable: ^2.0.5
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.0
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  
flutter:
  uses-material-design: true

